Monitor annotations
nf-osi/jobs pull request #25
Opened 2022-08-17 20:40 UTC by anngvu

Example test results:
- See emails in the NF service Google account

Some remaining issues/questions:

- [ ] Running into rate-limiting that would probably be better to handle
- [ ] Should DCC account be cc'd (this is default), or how else do we want to monitor emails sent out?
- [ ] Changes to email wording and formatting?

Reviewer development and testing notes:

- Build the image with e.g.  `docker build -t nfosi/jobs-monitor-anno .` (or pull image -- to be auto-built soon)
- Create an envfile `envfile-monitor-anno` as below and run `docker run  --env-file envfile-monitor-anno nfosi/jobs-monitor-anno`
- Can also generate tests in DEV mode (dry-run); use `PROFILE=DEV`

```
SCHEDULED_JOB_SECRETS={"SYNAPSE_AUTH_TOKEN":"XXX"}
PROFILE=TEST

# Optional params for reporting only
SCHEDULE=biweekly
SLACK=https://hooks.slack.com/services/XXX
```

2022-08-19 23:39 UTC, allaway commented
>  Should DCC account be cc'd (this is default), or how else do we want to monitor emails sent out?

What DCC account is this? I imagine this might create an overwhelming number of tickets if nf-osi@sagebionetworks.org. Maybe some other address? If it's not too difficult, a dedicated slack channel might actually be a good place for these notifications to go.

2022-08-19 23:40 UTC, allaway commented on monitor_annotations/helpers.R
> +    "Dear contributor,
```suggestion
    "Dear NF Data Portal contributor,
```

2022-08-19 23:42 UTC, allaway commented on monitor_annotations/helpers.R
> +  NF-OSI encourages that data files be annotated according to the docs here: https://help.nf.synapse.org/NFdocs/how-to-annotate-data.
```suggestion
  NF-OSI encourages (and many NF funders mandate) that data files are annotated so that they and future data users can understand what the data are.
  Please follow the annotation instructions here: https://help.nf.synapse.org/NFdocs/how-to-annotate-data.
```

2022-08-19 23:44 UTC, allaway commented on monitor_annotations/helpers.R
> +  You can ignore this reminder for any non-data files such as analyses and presentations.
I'm a little worried about this. Won't they get repeated notifications about any unannotated files? I think this might lead to them ignoring these messages.  I'm not sure how to address this problem.

2022-08-20 00:05 UTC, anngvu commented
Hey @allaway the DCC email that would be cc'd is nf-service@sagebase.org. You can also log in to see what the test emails look like from a couple days ago.

2022-08-20 00:10 UTC, anngvu commented on monitor_annotations/helpers.R
> +  You can ignore this reminder for any non-data files such as analyses and presentations.
Yeah, they get two weeks to resolve any un-annotated files. If there are still any at the next check, there will still be a reminder. One option is to move to more infrequent checks, maybe every 1-2 months. If they do not want reminders at all, a "do not remind" list can be maintained and referenced.

2022-08-20 00:33 UTC, allaway commented on monitor_annotations/helpers.R
> +  You can ignore this reminder for any non-data files such as analyses and presentations.
Hmm, maybe we can start out at one month? 

I wonder if it would make sense for us to - in monitoring these emails - do a minimal annotation of obvious non-data files for the contributors - eg. only annotating the resourceType of these `analysis` or `presentation`.

@jaybee84 what do you think?

2022-08-20 00:34 UTC, allaway commented
> Hey @allaway the DCC email that would be cc'd is [nf-service@sagebase.org](mailto:nf-service@sagebase.org). You can also log in to see what the test emails look like from a couple days ago.

Ah that makes sense. Sounds good, thanks!

2022-08-26 23:51 UTC, jaybee84 commented on monitor_annotations/helpers.R
> +  You can ignore this reminder for any non-data files such as analyses and presentations.
Sorry I missed this tag earlier! 

Re: frequency of annotation reminders
To me a 2-3 month cadence makes sense. One email every month may be too frequent and may lead to email blindness :)

Re: ResourceType annotation
This could be a check within this script. Once the script checks for new files, it could do a regex search in the filename and exclude any files with extension `.doc` or `.pdf` or `.pptx`. 
Annotating such files in-house may not be scalable, and may also be erroneous.

2022-08-27 00:10 UTC, jaybee84 requested changes

2022-08-27 00:10 UTC, jaybee84 commented on monitor_annotations/helpers.R
> +  names(files) <- studies$studyName
```suggestion
  names(files) <- studies$studyId
```

2022-08-27 00:10 UTC, jaybee84 commented on monitor_annotations/helpers.R
> +  names(files) <- studies$studyName
StudyNames are subject to change and have caused problems in previous instances

2022-09-13 15:57 UTC, anngvu commented on monitor_annotations/helpers.R
> +  names(files) <- studies$studyName
Not actually using study names to query, just using it as the display name in the email

2022-09-13 22:52 UTC, anngvu commented
Looked through the latest test batch and I think non-data files have been filtered out pretty effectively.

2022-09-20 14:53 UTC, merged